apiVersion: v1
kind: Service
metadata:
  name: vcluster-nodeport-4
  namespace: default
spec:
  selector:
    app: vcluster
    release: vcluster4
  ports:
    - name: https
      port: 443
      targetPort: 8443
      protocol: TCP
  type: NodePort
