apiVersion: v1
kind: Service
metadata:
  name: nodeport-1
  namespace: z2h
spec:
  selector:
    app: vcluster
    release: cluster1
  ports:
    - name: https
      port: 443
      targetPort: 8443
      protocol: TCP
  type: NodePort
