apiVersion: v1
kind: Service
metadata:
  name: nodeport-0
  namespace: z2h
spec:
  selector:
    app: vcluster
    release: cluster-0
  ports:
    - name: https
      port: 443
      targetPort: 8443
      nodePort: 32013
      protocol: TCP
  type: NodePort
